# Generated by Django 4.2.30 on 2026-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawMarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("opinet", "Opinet"),
                            ("yfinance", "Yahoo Finance"),
                            ("news", "News"),
                            ("manual", "Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("observed_at", models.DateTimeField()),
                ("value", models.DecimalField(decimal_places=4, max_digits=14)),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "raw_market_data",
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "symbol", "-observed_at"],
                        name="raw_market__source_7c0fe4_idx",
                    )
                ],
            },
        ),
    ]
