# Generated by Django 4.2.30 on 2026-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriceForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_date", models.DateField()),
                ("horizon_days", models.PositiveIntegerField()),
                ("model_name", models.CharField(default="baseline", max_length=50)),
                (
                    "predicted_price",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "lower_bound",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "upper_bound",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "price_forecast",
                "ordering": ["target_date", "horizon_days"],
                "indexes": [
                    models.Index(
                        fields=["target_date", "horizon_days"],
                        name="price_forec_target__e21b7e_idx",
                    ),
                    models.Index(
                        fields=["model_name"], name="price_forec_model_n_eae462_idx"
                    ),
                ],
            },
        ),
    ]
